In [1]:
import kagglehub
import pandas as pd
import os

# Download the dataset
path = kagglehub.dataset_download("waterwaterf/yelp-review-business")
print("Path to dataset files:", path)

# Load the business data
business_path = os.path.join(path, 'business.csv')
df_business = pd.read_csv(business_path)

# Load the review data
review_path = os.path.join(path, 'review_light (1).csv')
df_review = pd.read_csv(review_path)

# Display the first few rows of each
print("Business DataFrame:")
display(df_business.head())
print("\nReview DataFrame:")
display(df_review.head())

# Filter the business data for Philadelphia
df_business_Philadelphia = df_business[df_business['city'] == 'Philadelphia'].copy()

# Display the first few rows and the count
print(f"Number of businesses in Philadelphia: {len(df_business_Philadelphia)}")
display(df_business_Philadelphia.head())

# Filter reviews for businesses in Philadelphia
df_review_philadelphia = df_review[df_review['business_id'].isin(df_business_Philadelphia['business_id'])].copy()

# Display the first few rows and the count
print(f"Number of reviews for Philadelphia businesses: {len(df_review_philadelphia)}")
display(df_review_philadelphia.head())

Downloading to /root/.cache/kagglehub/datasets/waterwaterf/yelp-review-business/1.archive...

100%|██████████| 3.79G/3.79G [00:50<00:00, 80.5MB/s]

Extracting files...

Path to dataset files: /root/.cache/kagglehub/datasets/waterwaterf/yelp-review-business/versions/1
Business DataFrame:

,business_id,business_name,city,state,latitude,longitude,business_avg_stars,business_review_count
0,Pns2l4eNsfO8kk83dixA6A,"Abby Rappoport, LAC, CMQ",Santa Barbara,CA,34.426679,-119.711197,5.0,7
1,mpf3x-BjTdTEA3yCZrAYPw,The UPS Store,Affton,MO,38.551126,-90.335695,3.0,15
2,tUFrWirKiKi_TAnsVWINQQ,Target,Tucson,AZ,32.223236,-110.880452,3.5,22
3,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,Philadelphia,PA,39.955505,-75.155564,4.0,80
4,mWMc6_wTdE0EUBKIGXDVfA,Perkiomen Valley Brewery,Green Lane,PA,40.338183,-75.471659,4.5,13

Review DataFrame:

,review_id,user_id,business_id,stars,text,date
0,KU_O5udG6zpxOg-VcAEodg,mh_-eMZ6K5RLWhZyISBhwA,XQfwVwDr-v0ZS3_CbbE5Xw,3,"If you decide to eat here, just be aware it is...",2018-07-07 22:09:11
1,BiTunyQ73aT9WBnpR9DZGw,OyoGAe7OKpv6SyGZT5g77Q,7ATYjTIgM3jUlt4UM3IypQ,5,I've taken a lot of spin classes over the year...,2012-01-03 15:28:18
2,saUsX_uimxRlCVr67Z4Jig,8g_iMtfSiwikVnbP2etR0A,YjUWPpI6HXG530lwP-fb2A,3,Family diner. Had the buffet. Eclectic assortm...,2014-02-05 20:30:30
3,AqPFMleE6RsU23_auESxiA,_7bHUi9Uuf5__HHc_Q8guQ,kxX2SOes4o-D3ZQBkiMRfA,5,"Wow! Yummy, different, delicious. Our favo...",2015-01-04 00:01:03
4,Sx8TMOWLNuJBWer-0pcmoA,bcjbaE6dDog4jkNY91ncLQ,e4Vwtrqf-wpJfwesgvdgxQ,4,Cute interior and owner (?) gave us tour of up...,2017-01-14 20:54:15

Number of businesses in Philadelphia: 14569

,business_id,business_name,city,state,latitude,longitude,business_avg_stars,business_review_count
3,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,Philadelphia,PA,39.955505,-75.155564,4.0,80
15,MUTTqe8uqyMdBl186RmNeA,Tuna Bar,Philadelphia,PA,39.953949,-75.143226,4.0,245
19,ROeacJQwBeh05Rqg7F6TCg,BAP,Philadelphia,PA,39.943223,-75.162568,4.5,205
28,QdN72BWoyFypdGJhhI5r7g,Bar One,Philadelphia,PA,39.939825,-75.157447,4.0,65
31,Mjboz24M9NlBeiOJKLEd_Q,DeSandro on Main,Philadelphia,PA,40.022466,-75.218314,3.0,41

Number of reviews for Philadelphia businesses: 967552

,review_id,user_id,business_id,stars,text,date
1,BiTunyQ73aT9WBnpR9DZGw,OyoGAe7OKpv6SyGZT5g77Q,7ATYjTIgM3jUlt4UM3IypQ,5,I've taken a lot of spin classes over the year...,2012-01-03 15:28:18
3,AqPFMleE6RsU23_auESxiA,_7bHUi9Uuf5__HHc_Q8guQ,kxX2SOes4o-D3ZQBkiMRfA,5,"Wow! Yummy, different, delicious. Our favo...",2015-01-04 00:01:03
5,JrIxlS1TzJ-iCu79ul40cQ,eUta8W_HdHMXPzLBBZhL1A,04UD14gamNjLY0IDYVhHJg,1,I am a long term frequent customer of this est...,2015-09-23 23:10:31
13,8JFGBuHMoiNDyfcxuWNtrA,smOvOajNG0lS4Pq7d8g4JQ,RZtGWDLCAtuipwaZ-UfjmQ,4,Good food--loved the gnocchi with marinara\nth...,2009-10-14 19:57:14
16,oyaMhzBSwfGgemSGuZCdwQ,Dd1jQj7S-BFGqRbApFzCFw,YtSqYv1Q_pOltsVPSx54SA,5,Tremendous service (Big shout out to Douglas) ...,2013-06-24 11:21:25

In [3]:
# Identify the business with the highest review count
highest_review_business_id = top_10_businesses_philadelphia.iloc[0]['business_id']
highest_review_business_name = top_10_businesses_philadelphia.iloc[0]['business_name']

print(f"Extracting reviews for: {highest_review_business_name} (ID: {highest_review_business_id})")

# Filter df_review_philadelphia to get all reviews for this business
reviews_for_top_business = df_review_philadelphia[df_review_philadelphia['business_id'] == highest_review_business_id]

# Display the reviews
print(f"Total reviews for {highest_review_business_name}: {len(reviews_for_top_business)}")
display(reviews_for_top_business.head())

Extracting reviews for: Reading Terminal Market (ID: ytynqOUb3hjKeJfRj5Tshw)
Total reviews for Reading Terminal Market: 5778

,review_id,user_id,business_id,stars,text,date
6290881,kKC5pBPkUCWo6mKYFUewRw,mGnZFbk2gqLLtGW-mYo__A,ytynqOUb3hjKeJfRj5Tshw,5,I love this place! Doesn't take me long to get...,2016-08-25 16:30:53
6291053,sFQrhTbTah0o2kU_Pi2D0Q,Tu4ATXLhy8kRTjpQCnl2pA,ytynqOUb3hjKeJfRj5Tshw,5,"One of my favorite places to go to in Philly, ...",2016-07-14 20:24:15
6291157,kqn1uP3LRVjVDUD44ZSu1A,vRNb2IaGlsZRA_wUf3Ov8w,ytynqOUb3hjKeJfRj5Tshw,5,This might be a bit unfair to have a single re...,2017-04-07 22:27:22
6291166,qMsTe9QznpNQk1AKbYLp-w,29K-usmZfVDeIaQ85EG54A,ytynqOUb3hjKeJfRj5Tshw,4,"Alright, I remember the first time I went to t...",2017-07-18 17:33:29
6291460,nmMIRBNONIICe7CFHnfadQ,1jE--VcTddwXGampD23JCg,ytynqOUb3hjKeJfRj5Tshw,4,"It's an experience, to say the least! Not as ...",2013-08-03 20:18:22

In [6]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer, SnowballStemmer
from collections import Counter
import re

# Download necessary NLTK data (if not already downloaded)
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('punkt_tab') # Added this line

# Initialize stemmers and stopwords
porter = PorterStemmer()
snowball = SnowballStemmer('english')
stop_words = set(stopwords.words('english'))

def preprocess_text(text, stemmer=None):
    text = text.lower() # Convert to lowercase
    text = re.sub(r'[^a-z\s]', '', text) # Remove punctuation and numbers
    tokens = nltk.word_tokenize(text) # Tokenize
    tokens = [word for word in tokens if word not in stop_words] # Remove stop words
    if stemmer:
        tokens = [stemmer.stem(word) for word in tokens] # Apply stemming
    return tokens

# Process reviews without stemming
all_words_no_stem = []
for review_text in reviews_for_top_business['text']:
    all_words_no_stem.extend(preprocess_text(review_text))

# Process reviews with Porter Stemmer
all_words_porter_stem = []
for review_text in reviews_for_top_business['text']:
    all_words_porter_stem.extend(preprocess_text(review_text, porter))

# Process reviews with Snowball Stemmer
all_words_snowball_stem = []
for review_text in reviews_for_top_business['text']:
    all_words_snowball_stem.extend(preprocess_text(review_text, snowball))

# Get word frequency distributions
freq_dist_no_stem = Counter(all_words_no_stem)
freq_dist_porter = Counter(all_words_porter_stem)
freq_dist_snowball = Counter(all_words_snowball_stem)

print("\n--- Top 20 Words (No Stemming) ---")
display(pd.DataFrame(freq_dist_no_stem.most_common(20), columns=['Word', 'Frequency']))

print("\n--- Top 20 Words (Porter Stemmer) ---")
display(pd.DataFrame(freq_dist_porter.most_common(20), columns=['Word', 'Frequency']))

print("\n--- Top 20 Words (Snowball Stemmer) ---")
display(pd.DataFrame(freq_dist_snowball.most_common(20), columns=['Word', 'Frequency']))

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

--- Top 20 Words (No Stemming) ---

          Word  Frequency
0        place       4953
1         food       4071
2       market       3516
3        great       2268
4          get       1969
5       philly       1939
6           go       1930
7     terminal       1857
8      reading       1825
9          one       1691
10        love       1650
11        good       1494
12       fresh       1484
13        like       1399
14        many       1387
15         eat       1356
16        time       1318
17        best       1187
18  everything       1133
19      places       1115

--- Top 20 Words (Porter Stemmer) ---

      Word  Frequency
0    place       6075
1     food       4577
2   market       3891
3       go       2441
4      get       2360
5    great       2272
6   philli       1993
7     love       1926
8     good       1888
9      eat       1867
10    read       1867
11  termin       1862
12     one       1745
13    time       1652
14   visit       1556
15    like       1509
16   fresh       1498
17     tri       1455
18    shop       1431
19    mani       1387

--- Top 20 Words (Snowball Stemmer) ---

      Word  Frequency
0    place       6075
1     food       4577
2   market       3891
3       go       2441
4      get       2360
5    great       2276
6   philli       1993
7     love       1928
8     good       1888
9      eat       1867
10    read       1867
11  termin       1862
12     one       1745
13    time       1652
14   fresh       1582
15   visit       1556
16    like       1509
17     tri       1454
18    shop       1431
19    mani       1387

In [7]:
# Get the top 50 words from each distribution to ensure a good overlap of common terms
top_words_no_stem = set([word for word, freq in freq_dist_no_stem.most_common(50)])
top_words_porter = set([word for word, freq in freq_dist_porter.most_common(50)])
top_words_snowball = set([word for word, freq in freq_dist_snowball.most_common(50)])

# Combine all unique words from these top lists
all_common_words = sorted(list(top_words_no_stem.union(top_words_porter).union(top_words_snowball)))

# Create a list to store the data for the consolidated table
consolidated_data = []

for word in all_common_words:
    freq_no_stem = freq_dist_no_stem.get(word, 0)
    freq_porter = freq_dist_porter.get(porter.stem(word) if word in all_words_no_stem else word, 0)
    freq_snowball = freq_dist_snowball.get(snowball.stem(word) if word in all_words_no_stem else word, 0)

    # Attempt to find the stemmed version if the original word isn't found in stemmed lists
    if freq_porter == 0 and word not in freq_dist_porter:
        # Check if the word itself is a stem and exists in the porter list
        if porter.stem(word) in freq_dist_porter:
            freq_porter = freq_dist_porter.get(porter.stem(word))

    if freq_snowball == 0 and word not in freq_dist_snowball:
        # Check if the word itself is a stem and exists in the snowball list
        if snowball.stem(word) in freq_dist_snowball:
            freq_snowball = freq_dist_snowball.get(snowball.stem(word))

    consolidated_data.append({
        'Word/Stem': word,
        'Frequency (No Stemming)': freq_no_stem,
        'Frequency (Porter Stemmer)': freq_porter,
        'Frequency (Snowball Stemmer)': freq_snowball
    })

# Create the DataFrame
df_consolidated_frequencies = pd.DataFrame(consolidated_data)

# Sort by total frequency (or 'no stemming' frequency as a primary indicator of importance)
df_consolidated_frequencies['Total Frequency'] = df_consolidated_frequencies['Frequency (No Stemming)'] +\
                                                df_consolidated_frequencies['Frequency (Porter Stemmer)'] +\
                                                df_consolidated_frequencies['Frequency (Snowball Stemmer)']

df_consolidated_frequencies = df_consolidated_frequencies.sort_values(by='Total Frequency', ascending=False).drop(columns=['Total Frequency'])

print("\n--- Consolidated Word Frequencies Across Stemming Methods ---")
display(df_consolidated_frequencies.head(20)) # Display top 20 consolidated words

--- Consolidated Word Frequencies Across Stemming Methods ---

,Word/Stem,Frequency (No Stemming),Frequency (Porter Stemmer),Frequency (Snowball Stemmer)
47,place,4953,6075,6075
48,places,1115,6075,6075
23,food,4071,4577,4577
36,market,3516,3891,3891
28,great,2268,2272,2276
26,go,1930,2441,2441
25,get,1969,2360,2360
46,philly,1939,1993,1993
61,terminal,1857,1862,1862
52,reading,1825,1867,1867
31,love,1650,1926,1928
27,good,1494,1888,1888
40,one,1691,1745,1745
18,eat,1356,1867,1867
63,time,1318,1652,1652
24,fresh,1484,1498,1582
29,like,1399,1509,1509
35,many,1387,1387,1387
69,visit,932,1556,1556
45,philli,1,1993,1993

### Discussion of Stemming Results

Comparing the three sets of word frequency distributions:

1.  **Words without Stemming:**
    *   This list shows words exactly as they appear in the reviews (after lowercasing and removing punctuation/stopwords).
    *   You'll often see variations of the same root word (e.g., 'food', 'foods', 'eating') counted as separate entities.
    *   This provides a raw, unaggregated view of vocabulary usage.

2.  **Words obtained using Porter Stemmer:**
    *   The Porter Stemmer is a relatively aggressive stemming algorithm. It aims to reduce words to their common root form, often resulting in stems that are not actual dictionary words (e.g., 'restaur' from 'restaurant', 'locat' from 'location').
    *   You can observe that words like 'food', 'foods', 'eating' might all be reduced to a common stem, increasing the frequency count of that stem.
    *   While effective for reducing dimensionality, its aggressive nature can sometimes lead to loss of readability or semantic ambiguity.

3.  **Words obtained using Snowball Stemmer:**
    *   The Snowball Stemmer (also known as Porter2) is an improvement over the Porter Stemmer. It's generally considered less aggressive and more accurate, often producing stems that are closer to actual words.
    *   Similar to Porter, it groups word variations, but the resulting stems might be more recognizable.
    *   For example, 'restaurant' might be stemmed to 'restaur' by Porter, but 'restaurant' or 'resta' by Snowball, depending on its rules. It tries to balance reduction with maintaining linguistic meaning.

**Key Findings and Comparison:**

*   **Dimensionality Reduction:** Both stemming algorithms significantly reduce the number of unique tokens by grouping inflected forms of words. This is crucial for tasks like text classification or information retrieval, where you want to treat 'eat', 'eating', and 'eats' as the same concept.
*   **Frequency Aggregation:** By reducing words to their stems, the frequency counts for these stems increase, giving a more accurate representation of the prominence of a core concept rather than just specific word forms.
*   **Stem Quality:** The Snowball Stemmer generally produces more readable and accurate stems compared to the Porter Stemmer, which can sometimes create unusual or unrecognizable root forms. For applications where some interpretability of the stems is desired, Snowball might be preferred.
*   **Impact on Analysis:** Without stemming, analyses of word frequency might be diluted by many variations of the same word. Stemming helps to consolidate these, providing a clearer picture of the most important concepts or topics in the reviews. The choice between Porter and Snowball often depends on the specific language, the downstream NLP task, and the desired balance between aggressiveness and accuracy.