In [1]:
import kagglehub
import pandas as pd
import os

# Download the dataset
path = kagglehub.dataset_download("waterwaterf/yelp-review-business")
print("Path to dataset files:", path)

# Load the business data
business_path = os.path.join(path, 'business.csv')
df_business = pd.read_csv(business_path)

# Load the review data
review_path = os.path.join(path, 'review_light (1).csv')
df_review = pd.read_csv(review_path)

# Display the first few rows of each
print("Business DataFrame:")
display(df_business.head())
print("\nReview DataFrame:")
display(df_review.head())

# Filter the business data for Philadelphia
df_business_Philadelphia = df_business[df_business['city'] == 'Philadelphia'].copy()

# Display the first few rows and the count
print(f"Number of businesses in Philadelphia: {len(df_business_Philadelphia)}")
display(df_business_Philadelphia.head())

# Filter reviews for businesses in Philadelphia
df_review_philadelphia = df_review[df_review['business_id'].isin(df_business_Philadelphia['business_id'])].copy()

# Display the first few rows and the count
print(f"Number of reviews for Philadelphia businesses: {len(df_review_philadelphia)}")
display(df_review_philadelphia.head())
##%%

Downloading to /root/.cache/kagglehub/datasets/waterwaterf/yelp-review-business/1.archive...

100%|██████████| 3.79G/3.79G [02:23<00:00, 28.3MB/s]

Extracting files...

Path to dataset files: /root/.cache/kagglehub/datasets/waterwaterf/yelp-review-business/versions/1
Business DataFrame:

,business_id,business_name,city,state,latitude,longitude,business_avg_stars,business_review_count
0,Pns2l4eNsfO8kk83dixA6A,"Abby Rappoport, LAC, CMQ",Santa Barbara,CA,34.426679,-119.711197,5.0,7
1,mpf3x-BjTdTEA3yCZrAYPw,The UPS Store,Affton,MO,38.551126,-90.335695,3.0,15
2,tUFrWirKiKi_TAnsVWINQQ,Target,Tucson,AZ,32.223236,-110.880452,3.5,22
3,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,Philadelphia,PA,39.955505,-75.155564,4.0,80
4,mWMc6_wTdE0EUBKIGXDVfA,Perkiomen Valley Brewery,Green Lane,PA,40.338183,-75.471659,4.5,13

Review DataFrame:

,review_id,user_id,business_id,stars,text,date
0,KU_O5udG6zpxOg-VcAEodg,mh_-eMZ6K5RLWhZyISBhwA,XQfwVwDr-v0ZS3_CbbE5Xw,3,"If you decide to eat here, just be aware it is...",2018-07-07 22:09:11
1,BiTunyQ73aT9WBnpR9DZGw,OyoGAe7OKpv6SyGZT5g77Q,7ATYjTIgM3jUlt4UM3IypQ,5,I've taken a lot of spin classes over the year...,2012-01-03 15:28:18
2,saUsX_uimxRlCVr67Z4Jig,8g_iMtfSiwikVnbP2etR0A,YjUWPpI6HXG530lwP-fb2A,3,Family diner. Had the buffet. Eclectic assortm...,2014-02-05 20:30:30
3,AqPFMleE6RsU23_auESxiA,_7bHUi9Uuf5__HHc_Q8guQ,kxX2SOes4o-D3ZQBkiMRfA,5,"Wow! Yummy, different, delicious. Our favo...",2015-01-04 00:01:03
4,Sx8TMOWLNuJBWer-0pcmoA,bcjbaE6dDog4jkNY91ncLQ,e4Vwtrqf-wpJfwesgvdgxQ,4,Cute interior and owner (?) gave us tour of up...,2017-01-14 20:54:15

Number of businesses in Philadelphia: 14569

,business_id,business_name,city,state,latitude,longitude,business_avg_stars,business_review_count
3,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,Philadelphia,PA,39.955505,-75.155564,4.0,80
15,MUTTqe8uqyMdBl186RmNeA,Tuna Bar,Philadelphia,PA,39.953949,-75.143226,4.0,245
19,ROeacJQwBeh05Rqg7F6TCg,BAP,Philadelphia,PA,39.943223,-75.162568,4.5,205
28,QdN72BWoyFypdGJhhI5r7g,Bar One,Philadelphia,PA,39.939825,-75.157447,4.0,65
31,Mjboz24M9NlBeiOJKLEd_Q,DeSandro on Main,Philadelphia,PA,40.022466,-75.218314,3.0,41

Number of reviews for Philadelphia businesses: 967552

,review_id,user_id,business_id,stars,text,date
1,BiTunyQ73aT9WBnpR9DZGw,OyoGAe7OKpv6SyGZT5g77Q,7ATYjTIgM3jUlt4UM3IypQ,5,I've taken a lot of spin classes over the year...,2012-01-03 15:28:18
3,AqPFMleE6RsU23_auESxiA,_7bHUi9Uuf5__HHc_Q8guQ,kxX2SOes4o-D3ZQBkiMRfA,5,"Wow! Yummy, different, delicious. Our favo...",2015-01-04 00:01:03
5,JrIxlS1TzJ-iCu79ul40cQ,eUta8W_HdHMXPzLBBZhL1A,04UD14gamNjLY0IDYVhHJg,1,I am a long term frequent customer of this est...,2015-09-23 23:10:31
13,8JFGBuHMoiNDyfcxuWNtrA,smOvOajNG0lS4Pq7d8g4JQ,RZtGWDLCAtuipwaZ-UfjmQ,4,Good food--loved the gnocchi with marinara\nth...,2009-10-14 19:57:14
16,oyaMhzBSwfGgemSGuZCdwQ,Dd1jQj7S-BFGqRbApFzCFw,YtSqYv1Q_pOltsVPSx54SA,5,Tremendous service (Big shout out to Douglas) ...,2013-06-24 11:21:25

# 3.4 FAQ Generation Based on Reviews

This section generates FAQs from customer reviews for one randomly selected Philadelphia business. The selected business must have a reasonable number of reviews, preferably more than 100. The generated FAQs are based on frequently mentioned aspects and supporting review sentences.

In [2]:
# 3.4 FAQ Generation Based on Reviews
# Step 1: Check the Philadelphia sampled datasets

print("Philadelphia business dataset shape:", df_business_Philadelphia.shape)
print("Philadelphia review dataset shape:", df_review_philadelphia.shape)

print("\nBusiness columns:")
print(df_business_Philadelphia.columns.tolist())

print("\nReview columns:")
print(df_review_philadelphia.columns.tolist())

display(df_business_Philadelphia.head())
display(df_review_philadelphia.head())

Philadelphia business dataset shape: (14569, 8)
Philadelphia review dataset shape: (967552, 6)

Business columns:
['business_id', 'business_name', 'city', 'state', 'latitude', 'longitude', 'business_avg_stars', 'business_review_count']

Review columns:
['review_id', 'user_id', 'business_id', 'stars', 'text', 'date']

,business_id,business_name,city,state,latitude,longitude,business_avg_stars,business_review_count
3,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,Philadelphia,PA,39.955505,-75.155564,4.0,80
15,MUTTqe8uqyMdBl186RmNeA,Tuna Bar,Philadelphia,PA,39.953949,-75.143226,4.0,245
19,ROeacJQwBeh05Rqg7F6TCg,BAP,Philadelphia,PA,39.943223,-75.162568,4.5,205
28,QdN72BWoyFypdGJhhI5r7g,Bar One,Philadelphia,PA,39.939825,-75.157447,4.0,65
31,Mjboz24M9NlBeiOJKLEd_Q,DeSandro on Main,Philadelphia,PA,40.022466,-75.218314,3.0,41

,review_id,user_id,business_id,stars,text,date
1,BiTunyQ73aT9WBnpR9DZGw,OyoGAe7OKpv6SyGZT5g77Q,7ATYjTIgM3jUlt4UM3IypQ,5,I've taken a lot of spin classes over the year...,2012-01-03 15:28:18
3,AqPFMleE6RsU23_auESxiA,_7bHUi9Uuf5__HHc_Q8guQ,kxX2SOes4o-D3ZQBkiMRfA,5,"Wow! Yummy, different, delicious. Our favo...",2015-01-04 00:01:03
5,JrIxlS1TzJ-iCu79ul40cQ,eUta8W_HdHMXPzLBBZhL1A,04UD14gamNjLY0IDYVhHJg,1,I am a long term frequent customer of this est...,2015-09-23 23:10:31
13,8JFGBuHMoiNDyfcxuWNtrA,smOvOajNG0lS4Pq7d8g4JQ,RZtGWDLCAtuipwaZ-UfjmQ,4,Good food--loved the gnocchi with marinara\nth...,2009-10-14 19:57:14
16,oyaMhzBSwfGgemSGuZCdwQ,Dd1jQj7S-BFGqRbApFzCFw,YtSqYv1Q_pOltsVPSx54SA,5,Tremendous service (Big shout out to Douglas) ...,2013-06-24 11:21:25

In [3]:
# Step 2: Count the actual number of reviews for each Philadelphia business

review_counts = (
    df_review_philadelphia
    .groupby("business_id")
    .size()
    .reset_index(name="actual_review_count")
)

df_business_with_review_counts = df_business_Philadelphia.merge(
    review_counts,
    on="business_id",
    how="inner"
)

print("Number of Philadelphia businesses with at least one review:",
      len(df_business_with_review_counts))

display(df_business_with_review_counts.head())

Number of Philadelphia businesses with at least one review: 14569

,business_id,business_name,city,state,latitude,longitude,business_avg_stars,business_review_count,actual_review_count
0,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,Philadelphia,PA,39.955505,-75.155564,4.0,80,87
1,MUTTqe8uqyMdBl186RmNeA,Tuna Bar,Philadelphia,PA,39.953949,-75.143226,4.0,245,250
2,ROeacJQwBeh05Rqg7F6TCg,BAP,Philadelphia,PA,39.943223,-75.162568,4.5,205,208
3,QdN72BWoyFypdGJhhI5r7g,Bar One,Philadelphia,PA,39.939825,-75.157447,4.0,65,69
4,Mjboz24M9NlBeiOJKLEd_Q,DeSandro on Main,Philadelphia,PA,40.022466,-75.218314,3.0,41,41

In [4]:
# Step 3: Filter businesses with more than 100 actual reviews

MIN_REVIEWS = 100

eligible_businesses = df_business_with_review_counts[
    df_business_with_review_counts["actual_review_count"] > MIN_REVIEWS
].copy()

print(f"Number of eligible businesses with more than {MIN_REVIEWS} reviews:",
      len(eligible_businesses))

# Show top businesses by actual review count
display(
    eligible_businesses[
        ["business_id", "business_name", "city", "state",
         "business_avg_stars", "business_review_count", "actual_review_count"]
    ]
    .sort_values("actual_review_count", ascending=False)
    .head(10)
)

Number of eligible businesses with more than 100 reviews: 2177

,business_id,business_name,city,state,business_avg_stars,business_review_count,actual_review_count
13836,ytynqOUb3hjKeJfRj5Tshw,Reading Terminal Market,Philadelphia,PA,4.5,5721,5778
11041,PP3BBaVxZLcJU54uP_wL6Q,Pat's King of Steaks,Philadelphia,PA,3.0,4250,4293
5571,IkY2ticzHEn4QFn8hQLSWg,Geno's Steaks,Philadelphia,PA,2.5,3401,3428
12740,9PZxjhTIU7OgPIzuGi89Ew,El Vez,Philadelphia,PA,4.0,3187,3264
3053,ctHjyadbDQAtUFfkcAFEHw,Zahav,Philadelphia,PA,4.5,3065,3173
6271,6ajnOk0GcY9xbb5Ocaw8Gw,Barbuzzo,Philadelphia,PA,4.5,2893,2974
1978,j-qtdD55OLfSqfsWuQTDJg,Parc,Philadelphia,PA,4.0,2761,2884
5145,AGlh4ZDv6jnoiYfz7At9mw,Dim Sum Garden,Philadelphia,PA,4.0,2672,2778
5179,sTPueJEwcRDj7ZJmG7okYA,Jim's South St,Philadelphia,PA,3.5,2736,2769
14460,0RuvlgTnKFbX3IK0ZOOocA,Green Eggs Café,Philadelphia,PA,4.0,2679,2733

In [5]:
# Step 4: Randomly select one eligible business for FAQ generation

RANDOM_STATE = 42

selected_business = eligible_businesses.sample(
    n=1,
    random_state=RANDOM_STATE
).iloc[0]

b1_id = selected_business["business_id"]
b1_name = selected_business["business_name"]

print("Selected business for FAQ generation:")
print("Business ID:", b1_id)
print("Business Name:", b1_name)
print("City:", selected_business["city"])
print("State:", selected_business["state"])
print("Average Stars:", selected_business["business_avg_stars"])
print("Original Business Review Count:", selected_business["business_review_count"])
print("Actual Reviews in Philadelphia Dataset:", selected_business["actual_review_count"])

Selected business for FAQ generation:
Business ID: LM54ufrINJWoTN5imV8Etw
Business Name: John's Roast Pork
City: Philadelphia
State: PA
Average Stars: 4.5
Original Business Review Count: 1564
Actual Reviews in Philadelphia Dataset: 1609

In [6]:
# Step 5: Extract all reviews for the selected business

b1_reviews = df_review_philadelphia[
    df_review_philadelphia["business_id"] == b1_id
].copy()

print("Number of reviews extracted for selected business:", len(b1_reviews))

display(b1_reviews.head())

Number of reviews extracted for selected business: 1609

,review_id,user_id,business_id,stars,text,date
716207,lN2wWW8_lU-rvYoYjAhzkQ,XP5hqB6A9rvXlH_LHtzUgA,LM54ufrINJWoTN5imV8Etw,5,Now this is what I call a very good cheesestea...,2017-12-02 18:42:19
716621,2aFNSn4OqeQXXX61eDjdRg,jAMprJ2Z6Ah6Y4rHWaA73g,LM54ufrINJWoTN5imV8Etw,1,Tried their famous roasted pork sandwich. Not ...,2016-11-09 21:13:24
716687,ZlVMmO79xTxi0d6uzClsRg,zr6RSVAOfxRgVMdkjEYQXw,LM54ufrINJWoTN5imV8Etw,1,"If you want a great cheesesteak, Johns is the ...",2017-06-06 20:05:48
716740,Szkz8cHBXXcVYSYDCN7y7w,-2Ro3V4zgRZa92tPI5ul7Q,LM54ufrINJWoTN5imV8Etw,5,"Yep, this is the best roast pork sammich there...",2015-07-16 13:24:41
716823,VM6R-fTDwbGdUfA0fpIZqQ,rqY0AQMUtoDQnfgxCNuKgw,LM54ufrINJWoTN5imV8Etw,5,Outstanding. Pizza Steak with onions is Delis...,2011-04-22 01:57:46

In [20]:
# Step 6: Basic statistics for the selected business reviews

b1_reviews["review_length_words"] = b1_reviews["text"].astype(str).apply(
    lambda x: len(x.split())
)

review_stats = {
    "business_id": b1_id,
    "business_name": b1_name,
    "number_of_reviews": len(b1_reviews),
    "average_review_stars": b1_reviews["stars"].mean(),
    "average_review_length_words": b1_reviews["review_length_words"].mean(),
    "median_review_length_words": b1_reviews["review_length_words"].median(),
    "min_review_length_words": b1_reviews["review_length_words"].min(),
    "max_review_length_words": b1_reviews["review_length_words"].max()
}

review_stats_df = pd.DataFrame([review_stats])
display(review_stats_df)

,business_id,business_name,number_of_reviews,average_review_stars,average_review_length_words,median_review_length_words,min_review_length_words,max_review_length_words
0,LM54ufrINJWoTN5imV8Etw,John's Roast Pork,1609,4.333748,106.293971,77.0,4,853

In [10]:
# Step 7: Import NLP tools for sentence tokenization

import re
import nltk
from nltk.tokenize import sent_tokenize

# Download tokenizer resources if needed
nltk.download("punkt")
nltk.download("punkt_tab")

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [11]:
# Step 8: Split reviews into sentences

sentences = []

for _, row in b1_reviews.iterrows():
    review_id = row["review_id"]
    stars = row["stars"]
    text = str(row["text"])

    for sent in sent_tokenize(text):
        clean_sent = sent.strip()

        # Keep only meaningful sentences
        if len(clean_sent.split()) >= 5:
            sentences.append({
                "review_id": review_id,
                "stars": stars,
                "sentence": clean_sent
            })

sentences_df = pd.DataFrame(sentences)

print("Number of review sentences extracted:", len(sentences_df))
display(sentences_df.head())

Number of review sentences extracted: 11036

,review_id,stars,sentence
0,lN2wWW8_lU-rvYoYjAhzkQ,5,Now this is what I call a very good cheesesteak.
1,lN2wWW8_lU-rvYoYjAhzkQ,5,You can see them making your sandwich with cho...
2,lN2wWW8_lU-rvYoYjAhzkQ,5,"As expected, the chopped beef rather than slic..."
3,lN2wWW8_lU-rvYoYjAhzkQ,5,Definitely a must try at this place.
4,lN2wWW8_lU-rvYoYjAhzkQ,5,Another outstanding sandwich is the Roast Pork.

In [12]:
# Step 9: Define common restaurant/business review aspects and keywords

ASPECT_KEYWORDS = {
    "food quality": [
        "food", "dish", "dishes", "taste", "tasty", "flavor", "flavors",
        "delicious", "fresh", "meal", "meals", "yummy", "quality"
    ],
    "service": [
        "service", "staff", "server", "servers", "waiter", "waitress",
        "employee", "employees", "friendly", "rude", "attentive", "helpful"
    ],
    "price and value": [
        "price", "prices", "priced", "expensive", "cheap", "worth",
        "value", "cost", "overpriced", "affordable"
    ],
    "waiting time": [
        "wait", "waited", "waiting", "line", "queue", "slow", "quick",
        "fast", "busy", "crowded"
    ],
    "ambience": [
        "atmosphere", "ambience", "ambiance", "vibe", "decor", "interior",
        "music", "noise", "noisy", "quiet", "cozy", "clean"
    ],
    "portion size": [
        "portion", "portions", "size", "serving", "servings", "amount",
        "large", "small", "huge", "generous"
    ],
    "menu options": [
        "menu", "options", "option", "variety", "selection",
        "vegetarian", "vegan", "gluten", "special", "specials"
    ],
    "location and parking": [
        "location", "parking", "park", "street", "lot", "area",
        "neighborhood", "nearby", "downtown"
    ]
}

QUESTION_TEMPLATES = {
    "food quality": "How do customers describe the food quality?",
    "service": "How is the service at this business?",
    "price and value": "Do customers think this business is good value for money?",
    "waiting time": "Do customers mention long waiting times?",
    "ambience": "What is the atmosphere like?",
    "portion size": "Are the portions large?",
    "menu options": "Are there enough menu options?",
    "location and parking": "Is the location or parking convenient?"
}

In [13]:
# Step 10: Match review sentences to each aspect

def normalize_text(text):
    """
    Lowercase text and remove extra spaces.
    """
    text = str(text).lower()
    text = re.sub(r"\s+", " ", text)
    return text.strip()


def sentence_matches_keywords(sentence, keywords):
    """
    Check whether a sentence contains any keyword from the given keyword list.
    Uses simple word-boundary matching to reduce false matches.
    """
    sentence_lower = normalize_text(sentence)

    for keyword in keywords:
        keyword_lower = keyword.lower()
        pattern = r"\b" + re.escape(keyword_lower) + r"\b"
        if re.search(pattern, sentence_lower):
            return True

    return False


aspect_sentence_matches = {}

for aspect, keywords in ASPECT_KEYWORDS.items():
    matched_df = sentences_df[
        sentences_df["sentence"].apply(
            lambda sent: sentence_matches_keywords(sent, keywords)
        )
    ].copy()

    aspect_sentence_matches[aspect] = matched_df

    print(f"{aspect}: {len(matched_df)} matched sentences")

food quality: 1173 matched sentences
service: 336 matched sentences
price and value: 316 matched sentences
waiting time: 911 matched sentences
ambience: 68 matched sentences
portion size: 492 matched sentences
menu options: 171 matched sentences
location and parking: 509 matched sentences

In [14]:
# Step 11: Select aspects with enough supporting evidence

MIN_MATCHED_SENTENCES = 10
MAX_FAQS = 8

aspect_summary = []

for aspect, matched_df in aspect_sentence_matches.items():
    aspect_summary.append({
        "aspect": aspect,
        "matched_sentence_count": len(matched_df),
        "average_stars_of_matched_reviews": matched_df["stars"].mean()
            if len(matched_df) > 0 else None
    })

aspect_summary_df = pd.DataFrame(aspect_summary).sort_values(
    "matched_sentence_count",
    ascending=False
)

display(aspect_summary_df)

selected_aspects = aspect_summary_df[
    aspect_summary_df["matched_sentence_count"] >= MIN_MATCHED_SENTENCES
]["aspect"].head(MAX_FAQS).tolist()

print("Selected aspects for FAQ generation:")
print(selected_aspects)

,aspect,matched_sentence_count,average_stars_of_matched_reviews
0,food quality,1173,4.231032
3,waiting time,911,4.222832
7,location and parking,509,4.339882
5,portion size,492,4.339431
1,service,336,3.601190
2,price and value,316,4.313291
6,menu options,171,3.912281
4,ambience,68,4.132353

Selected aspects for FAQ generation:
['food quality', 'waiting time', 'location and parking', 'portion size', 'service', 'price and value', 'menu options', 'ambience']

In [15]:
# Step 12: Select representative evidence sentences

def select_evidence_sentences(matched_df, max_evidence=3):
    """
    Select representative review sentences as supporting evidence.
    The selection keeps sentences with reasonable length and avoids duplicate reviews.
    """
    if matched_df.empty:
        return []

    temp = matched_df.copy()
    temp["word_count"] = temp["sentence"].apply(lambda x: len(str(x).split()))

    # Keep sentences with reasonable length for report readability
    temp = temp[
        (temp["word_count"] >= 8) &
        (temp["word_count"] <= 40)
    ].copy()

    if temp.empty:
        temp = matched_df.copy()

    # Prefer sentences from different reviews
    temp = temp.drop_duplicates(subset=["review_id"])

    # Sort by star rating distance from the average to include clear opinions
    # This is optional; it helps select more opinionated sentences.
    temp["star_distance_from_neutral"] = (temp["stars"] - 3).abs()
    temp = temp.sort_values(
        ["star_distance_from_neutral", "word_count"],
        ascending=[False, True]
    )

    evidence = temp.head(max_evidence)["sentence"].tolist()
    return evidence

In [16]:
# Step 13: Generate short answers based on matched review evidence

def generate_answer(aspect, matched_df):
    """
    Generate a conservative answer based on the number and rating distribution
    of review sentences matched to an aspect.
    """
    count = len(matched_df)

    if count == 0:
        return "There is not enough review evidence to answer this question."

    avg_stars = matched_df["stars"].mean()

    positive_count = len(matched_df[matched_df["stars"] >= 4])
    neutral_count = len(matched_df[matched_df["stars"] == 3])
    negative_count = len(matched_df[matched_df["stars"] <= 2])

    positive_ratio = positive_count / count
    negative_ratio = negative_count / count

    if positive_ratio >= 0.65:
        tendency = "Most related comments appear in positive reviews."
    elif negative_ratio >= 0.45:
        tendency = "A noticeable number of related comments appear in lower-rated reviews."
    else:
        tendency = "Customer opinions on this aspect appear to be mixed."

    aspect_phrases = {
        "food quality": "food quality",
        "service": "service",
        "price and value": "price and value",
        "waiting time": "waiting time",
        "ambience": "the atmosphere",
        "portion size": "portion size",
        "menu options": "menu options",
        "location and parking": "location or parking"
    }

    aspect_text = aspect_phrases.get(aspect, aspect)

    answer = (
        f"{aspect_text.capitalize()} is mentioned in {count} review sentences. "
        f"The average rating of the reviews mentioning this aspect is {avg_stars:.2f}. "
        f"{tendency}"
    )

    return answer

In [17]:
# Step 14: Generate FAQ items

faq_items = []

for aspect in selected_aspects:
    matched_df = aspect_sentence_matches[aspect]

    question = QUESTION_TEMPLATES.get(
        aspect,
        f"What do customers say about {aspect}?"
    )

    answer = generate_answer(aspect, matched_df)
    evidence = select_evidence_sentences(matched_df, max_evidence=3)

    faq_items.append({
        "Aspect": aspect,
        "Question": question,
        "Answer": answer,
        "Matched_Sentence_Count": len(matched_df),
        "Evidence_1": evidence[0] if len(evidence) > 0 else "",
        "Evidence_2": evidence[1] if len(evidence) > 1 else "",
        "Evidence_3": evidence[2] if len(evidence) > 2 else ""
    })

faq_df = pd.DataFrame(faq_items)

display(faq_df)

,Aspect,Question,Answer,Matched_Sentence_Count,Evidence_1,Evidence_2,Evidence_3
0,food quality,How do customers describe the food quality?,Food quality is mentioned in 1173 review sente...,1173,Now this is a cheese steak with FLAVOR.,They also have a delicious roast pork sammich.,"Like others have said, the food is great."
1,waiting time,Do customers mention long waiting times?,Waiting time is mentioned in 911 review senten...,911,They give you attitude bc they're so busy.,The line was out the door but moving.,although the wait time is way too crazy.
2,location and parking,Is the location or parking convenient?,Location or parking is mentioned in 509 review...,509,"If you're ever in the area, stop by!",Street parking is available and they take card.,On East Snyder street not far off 95.
3,portion size,Are the portions large?,Portion size is mentioned in 492 review senten...,492,"Incredible amount of food for the price, too.","I couldn't even finish it, it was huge.",The large is easily split between two people.
4,service,How is the service at this business?,Service is mentioned in 336 review sentences. ...,336,"Horrible service, rude staff and bad Pork Roast!",Best cheesesteak in the world and awesome staff.,It was simple to order with courteous staff.
5,price and value,Do customers think this business is good value...,Price and value is mentioned in 316 review sen...,316,"Incredible amount of food for the price, too.",Totally worth the trip from New York !,but if you have the time....its worth it.
6,menu options,Are there enough menu options?,Menu options is mentioned in 171 review senten...,171,One special thing about John's is their rolls.,"Did that special sauce say ""Summers Eve"" on it?",They offer a nice selection for a great price!!
7,ambience,What is the atmosphere like?,The atmosphere is mentioned in 68 review sente...,68,"The bread, the meat, meat portion and ambiance.",Great atmosphere and in the heart of South Phi...,The food is stellar and the atmosphere is real...

In [18]:
# Step 15: Export FAQ generation results

faq_output_path = "faq_generation_results.csv"
faq_df.to_csv(faq_output_path, index=False)

print(f"FAQ generation results saved to: {faq_output_path}")

FAQ generation results saved to: faq_generation_results.csv

In [19]:
# Step 16: Create a concise FAQ table for the report

faq_report_df = faq_df[
    ["Aspect", "Question", "Answer", "Evidence_1"]
].copy()

display(faq_report_df)

,Aspect,Question,Answer,Evidence_1
0,food quality,How do customers describe the food quality?,Food quality is mentioned in 1173 review sente...,Now this is a cheese steak with FLAVOR.
1,waiting time,Do customers mention long waiting times?,Waiting time is mentioned in 911 review senten...,They give you attitude bc they're so busy.
2,location and parking,Is the location or parking convenient?,Location or parking is mentioned in 509 review...,"If you're ever in the area, stop by!"
3,portion size,Are the portions large?,Portion size is mentioned in 492 review senten...,"Incredible amount of food for the price, too."
4,service,How is the service at this business?,Service is mentioned in 336 review sentences. ...,"Horrible service, rude staff and bad Pork Roast!"
5,price and value,Do customers think this business is good value...,Price and value is mentioned in 316 review sen...,"Incredible amount of food for the price, too."
6,menu options,Are there enough menu options?,Menu options is mentioned in 171 review senten...,One special thing about John's is their rolls.
7,ambience,What is the atmosphere like?,The atmosphere is mentioned in 68 review sente...,"The bread, the meat, meat portion and ambiance."